### ISSUE TITLE
Exclude CAM releases option.

### ISSUE THREAD

**Issue by isthisausername2** [itsToggle/plex_debrid#126]
Hello,

I have plex_debird setup and working but occasionally it will grab a cam release from my added sources.

I understand there may be a way to do this using the setting in ``Options/Settings/Scraper Settings/Release sorting`` but i am unsure of how this would be formated to remove cam releases. 

This issue is similar to [this issue](https://github.com/itsToggle/plex_debrid/issues/98) but i am just looking for a way to exclude cam releases, while it would be nice to have an easier way to control what media is added the defaults are working fine for me.

I would also like to say thank you for the time and effort put into this script and how well it works and how quickly it is able to add media to my plex library.

**Comment by Selmer443** [comment]
you can remove CAM releases by adding a release sorting rule like so : ['(CAM|HDCAM)', 'title', 'text', '0'], also note, this is just how the rule should look when you are finished adding it inside your release sorting rules. I'll write out the exact steps and what you should enter at each step from the start screen which displays the 4 options (run, settings, ignored media, scraper). I also added the HDCAM phrase because this is another common label for CAM releases. 
Steps: 
1. (Start Screen) : Press 2 and press enter to open "Settings"
2. (Settings): Press 3 and press enter to open "Scraper Settings"
3. (Scraper Settings): Press 2 and press enter to open "Release sorting"
4. (Release sorting): Press 1 and press enter to open edit option
5. Press 1 and enter to open "Add rule"
6. Type (CAM|HDCAM) to provide regex match group
7. Type title to specify the release attribute
8. Type text to specify that this attribute will be specified as text rather than number 
9. Type 0 to rank this sorting rule as ascending 
(You should now be back at the settings screen, we still need to move the sorting rule to the first position to give it the highest priority)
10. (Settings): Press 3 and press enter to open "Scraper Settings" once again
11. (Scraper Settings) Press 2 and press enter to open "Release sorting" 
12. (Release sorting): Press 1 and enter to open edit option
13. Press 2 and press enter to Edit rules
You will now need to find the number corresponding to the rule you just added, by default the rules are added in the lowest priority (or the highest number) for the next set of instructions I will specify this number as "number". 
14. Enter the number corresponding to your rule "number" to edit the rule (for me this is 13, it may be different for you depending how many rules you have)
15. You should now see a prompt with 4 options (Back, Edit, Delete, Move) We want to select move, so press 3 and then press enter
16. You want to move this rule to Position 1 so it has the highest priority, Press 1 and then press enter

You can now verify your release sorting rules by navigating back into Options/Settings/Scraper Settings/Release sorting and viewing the rules. CAM|HDCAM should be listed at the top.

**Comment by itsToggle** [comment]
This answer is great, and probably more detailed than I could have written it. Thanks @Selmer443!
