### ISSUE TITLE
Prowlarr slow scraping times

### ISSUE THREAD

**Issue by joshali1990** [itsToggle/plex_debrid#128]
It seems like whenever Prowlarr has to scrape more than one release it ends up taking a ton of time for the subsequent searches. Not sure if this has to do with Prowlarr's rate limiting. 

[2022-09-19 12:18:17.261737] [realdebrid] adding cached release: City.on.a.Hill.S03E07.1080p.WEB.H264-GGEZ[rartv]
[2022-09-19 12:18:18.453140] took 13.96s
[2022-09-19 12:18:18.453296] refreshing library section 1
[2022-09-19 12:18:19.323166] scraping sources for query "house.of.the.dragon.S01" ... done - found 251 releases
[2022-09-19 12:20:15.424780] attempting to download version 1/1: "(1080p)" ... done
[2022-09-19 12:20:17.160668] [realdebrid] adding cached release: House.of.the.Dragon.S01E05.We.Light.the.Way.1080p.HMAX.WEBRip.DDP5.1.x264-NTb[rartv]
[2022-09-19 12:20:18.617663] took 119.3s

**Comment by itsToggle** [comment]
Thanks for reporting! This will indeed be caused by prowlarrs rate limiting. When prowlarr is done scraping, plex_debrid needs to make another call to get the torrent files or magnet links for the scraped releases to be able to check if each release is cached on your debrid service. This step is heavily rate limited by prowlarr and can take minutes. What I did to solve this, is simply time out the request to prowlarr after 10 seconds or so and only work with the releases it returns during this time. 
As you point out, it seems that prowlarr will continue this operation in the background though, which is why it will take a lot of time when you try to scrape for another release.

I'll try to solve this, but in the meantime: why not switch to jackett? It's a lot faster because it does not have these restrictions. It will also allow you to find more cached releases, since all releases that jackett can find will be checked against your debrid services.

**Comment by itsToggle** [comment]
Alright so the only thing I can think of is limiting the amount of releases for which prowlarr will be tasked to find the torrent file/magnet link for. Ive chosen to not do this before, because depending on the indexers you integrate into prowlarr you might be able to gather more releases than the limit I will arbitrarily set. 
If you want me to do this I will, but again, I would suggest switching to jackett (at least for plex_debrid).

**Comment by joshali1990** [comment]
Thanks for looking into this. I was using Prowlarr since Jackett randomly deletes my indexers sometimes. Not a huge problem, so I think you can leave Prowlarr alone and I'll just switch back to Jackett. You can close the issue.
