### ISSUE TITLE
Use trakt history to skip download in addition to trakt collection

### ISSUE THREAD

**Issue by krishne35** [itsToggle/plex_debrid#176]
Presently implementation only checks for trakt collection to check weather to download or skip the content from the watchlist/user list 
It will be useful if it check the trakt history too

**Comment by itsToggle** [comment]
a little more complicated than I initially thought, since trakt does not provide any "watched" attribute when getting movies/shows from the watchlist or the collection. a seperate call needs to be made in order to determine the watch status for each movie and each show. Its still possible to implement this though.

**Comment by itsToggle** [comment]
implemented a the trakt watch status, aswell as an optional local file as "library ignore services". This update is currently in testing and is actively worked on, you could already check it out on the experimental branch. There will be bugs though.

**Comment by itsToggle** [comment]
implemented in v2.20
