### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by BluePotatoBP** [itsToggle/plex_debrid#18]
Sorry for spamming the issues but eh, what can you do...

The script doesn't have permissions to access settings.json
![image](https://user-images.githubusercontent.com/52742857/173167236-aaec1316-187c-46eb-bb95-9f7a66efd264.png)

This one I genuinely don't know how to fix, because if I open an admin cmd it will say it's missing modules but if I right click and open with python it doesn't have permissions, unless this is something completely different.

**Comment by itsToggle** [comment]
Hm, Ive never encountered this. Here's a suggestion that I found: Change the permissions of the directory you want to save to so that all users have read and write permissions.
Other than that I might need to investigate wether or not i close the file correctly after writing to it.

**Comment by BluePotatoBP** [comment]
Yeah I checked the user permissions, and they are allowed to read and write but there is also this attribute called `read-only ` that won't let me uncheck it, that is, it re-enables itself after I close the window. Also moving directories didn't help.

![image](https://user-images.githubusercontent.com/52742857/173194910-5f1ac92d-f080-462a-920f-b46f32721b06.png)
![image](https://user-images.githubusercontent.com/52742857/173194929-72c2b560-31b2-4dfd-b8aa-411923e9095f.png)

**Comment by itsToggle** [comment]
That's weird. Let's try to fix the admin-cmd missing modules then.. have you tried opening other python scripts within the admin cmd? Do they report modules as missing? You coukld try to install the missing modules while in admin cmd, so the modules are installed for the admin user (which by default they should be, even when running without admin privileges). You could try to reinstall python, since something seems to be broken.
There is sadly not much I can do inside the script. It needs to save your settings somehow and write permission is required for that. I could make the script request admin privileges, but that would lead to your current python install saying it's missing modules.

**Comment by itsToggle** [comment]
I just saw the other issue that youve closed already. The problem is definitely somewhere in your python installation. It seems you have multiple versions of python installed, try to uninstall one of them. Or uninstall both and start fresh :)

**Comment by BluePotatoBP** [comment]
See there's this funny button I seem to have missed when installing python again
![image](https://user-images.githubusercontent.com/52742857/173237901-9b0f0635-b630-4a2f-b73b-f5e0f18a5613.png)

Yeah it just didn't update the PATH variable.

Btw, I know it might not be the best place to ask for features but could you automate the missing module installation? Or at least show every module that's missing instead of displaying them one at a time. I'm sure it would save some time for new users.

**Comment by BluePotatoBP** [comment]
Now I'm having issues with it ignoring basically anything? I tried a show first, then this random movie and it just kept ignoring anything it found. 
![image](https://user-images.githubusercontent.com/52742857/173241378-ee8624c0-316d-43c7-ba59-af936e69bc36.png)

**Comment by BluePotatoBP** [comment]
And the same result with jackett. I have a suspicion I configured something wrong...
![image](https://user-images.githubusercontent.com/52742857/173249214-b3fd212f-d831-4132-bd06-e82b22d0e47c.png)

In case you'd like to look at my settings: https://hastebin.skyra.pw/oguloyiyeb.prolog
(github wouldn't let me upload a json file)

Also, these are my indexers, if needed.
![image](https://user-images.githubusercontent.com/52742857/173249425-21069382-e3c5-4360-ba83-1de030d1ea69.png)

**Comment by itsToggle** [comment]
That does indeed look like some sort of miss-configuration. I tried adding both those movies just in case and on my end it works (see pic). I cant see the settings file anymore, but I did have a look yesterday and didnt notice anything too wrong. Could you re-upload your settings again though?
The problem is most likely within your debrid service settings, since the scraper/s do return releases. 
![hm](https://user-images.githubusercontent.com/71379623/173299104-786dc58e-a7e5-425f-901d-131f7e7eed16.png)

**Comment by BluePotatoBP** [comment]
Oh I guess hastebin deletes posts after a while? Here's a permanent pastebin: https://pastebin.com/CrL9fhAK

**Comment by itsToggle** [comment]
Thank you! Those settings look fine. Would you mind turning on 'debug printing' in the 'UI Settings' section of the 'Settings' Menu? This setting will print more of the stuff that its doing and should give us a bit more information on whats going wrong :)

**Comment by itsToggle** [comment]
Ah thats the problem. You don't have a premium account. You need premium to use any of the features, which costs about 3€/month :)

**Comment by BluePotatoBP** [comment]
Dang, thanks for the help! Yeah I'll get premium.

**Comment by BluePotatoBP** [comment]
Oh man, sorry I bought it like 30 seconds before I got the message. Do you have a bitcoin address I could donate to?

**Comment by itsToggle** [comment]
Not a problem at all haha! I don't have bitcoin, but you dont need to donate anything. Seems like this script has caused you enough trouble already :D
