### ISSUE TITLE
Latest docker container fails to start

### ISSUE THREAD

**Issue by matustokar** [itsToggle/plex_debrid#221]
`docker run -ti itstoggle/plex_debrid -v /storage/docker/plexDebrid:/settings.json`

results in

```
docker: Error response from daemon: OCI runtime create failed: runc create failed: unable to start container process: exec: "-v": executable file not found in $PATH: unknown.
ERRO[0001] error waiting for container: context canceled 
```

**Comment by itsToggle** [comment]
Has that command worked for you before? If so, on what version? I didn't actually change anything regarding the dockerfile and the build was successful according to GitHub Actions

**Comment by itsToggle** [comment]
Perhaps just pull it again?

**Comment by sonofmp3** [comment]
I also could not get the command, docker run -ti plex_debrid -v /path/on/host:/settings.json, supplementing the local volume path to work. 

So, I built it with portainer (https://hub.docker.com/r/portainer/portainer-ce).


Portainer settings are as below:

Image: itstoggle/plex_debrid:latest

![portainer#1](https://user-images.githubusercontent.com/36779668/199377158-59eae617-3240-40b3-9b74-298b2e98c722.PNG)

Command & logging:
-Command: Override: 'python' './main.py' '-e' 'TERM=xterm'
-Entrypoint: Override
-Console: Interactive & TTY

![portainer#2](https://user-images.githubusercontent.com/36779668/199377962-cb8fdb87-aec3-4067-82d0-35cab0e8dc3e.PNG)

Volumes:
container: /settings.json -> Bind
host: whatever local path you want, but include settings.json (described in the next part) -> Writable

![portainer#3](https://user-images.githubusercontent.com/36779668/199378384-09ce82b6-c67e-4a37-99a7-8bc42b3a441c.PNG)

The settings.json file needs to be in the host directory for the container to start. Otherwise, it will have the following error when starting and immediately shutdown:

![portainer#4](https://user-images.githubusercontent.com/36779668/199384896-45dbdbfa-77bb-43fc-ac28-c4fe26eb8031.PNG)

It will also create a director in the host volume named settings.json

I'm not certain of the root cause, but I believe it may be due to the settings.json not existing in the container because it's generated after the initial setup and docker not recognizing the missing settings.json as a file.

Therefore, the settings.json must exist in the host volume prior to the start/initial setup.   

As such, the attached zip with the stipped settings.json will allow the container to load. 

[settings.zip](https://github.com/itsToggle/plex_debrid/files/9915589/settings.zip)

With the container now running, enter the container console and enter the following command:
python ./main.py -e TERM=xterm

![portainer#7](https://user-images.githubusercontent.com/36779668/199388644-66ffd53e-31f5-456b-8d7f-9ce3ca76c6d8.PNG)


From there you will be able to change all the settings, which will be written to the file in the host directory. 

![portainer#5](https://user-images.githubusercontent.com/36779668/199387344-da06cb22-e812-47a9-b3c2-7912dfcc7e98.PNG)

If you'd prefer to have plex_derbid start automatically each time the container starts, then ensure you set "Show Menu on Startup" to false. 

Otherwise, you will need to start plex_debrid from the container console each time using the previous command. 

The former will also allow you to view the ui printout in the logs.

![portainer#6](https://user-images.githubusercontent.com/36779668/199388176-dbd384a9-4efc-4899-bc33-cd37bb1e02a7.PNG)

Enjoy!

**Comment by itsToggle** [comment]
This is great! Thanks! :)

I did a bit of googling and it seems that `docker run -ti itstoggle/plex_debrid -v /storage/docker/plexDebrid:/settings.json` will interpret the "-v" as the container you want to run. chaning the command to `docker run -v /storage/docker/plexDebrid:/settings.json -ti itstoggle/plex_debrid` could have possibly solved your initial issue aswell.

How do other docker containers use configuration files? Would it be possible to create the settings.json file from within the container on the host sytstem or on a docker volume, so there is no need to touch an empty file beforehand?

**Comment by magnu5** [comment]
other docker containers use a 'config' directory, in your case settings.json would be inside that dir. Then we could map that to a volume:
`docker run -v /mnt/user/appdata/plex_debrid/:/config -ti itstoggle/plex_debrid`
tried running the docker on unraid but got the same error as op. I think that change might solve it as you cannot map anything other than absolute paths as volumes in docker.

**Comment by itsToggle** [comment]
alright! To keep compatability for current setups, I could make plex_debrid look for settings.json in both the root and a /config folder.

**Comment by itsToggle** [comment]
okay I think I might have fixed this. The dockerfile now passes an argument to main.py, that sets the directory for "settings.json" to "/config" if the file does not already exist in the root directory. 

Any of you guys mind trying this out? You would need to clone the experimental branch, build the docker image, and then run `docker run -v /mnt/user/appdata/plex_debrid/:/config -ti itstoggle/plex_debrid`

**Comment by itsToggle** [comment]
Just realized that this will only work if you create a /config directory in the "plex_debrid-experimental" folder before building the docker image, since I cant add empty folders to github.

**Comment by itsToggle** [comment]
Nevermind, this should work.

**Comment by itsToggle** [comment]
solved
