### ISSUE TITLE
Release not found even if scrapper (prowlarr) finds some

### ISSUE THREAD

**Issue by JULIENBZH** [itsToggle/plex_debrid#233]
Looking for a film, plex_debrid says found 0 release but when I search the exact expression in prowlarr it finds plenty of files. It only happens with some content, the connection between plex_debrid and prowlarr is working fine for other research...

**Comment by JULIENBZH** [comment]
Thank you for your answer, I understand now but I still don't see where it doesn't match : 

-  plex_debrid returns : 

scraping sources for query "une.sirene.à.paris.2020" ... done - found 0 releases

- while, Prowlarr gives me : 

[Une.Sirene.a.Paris.2020.FRENCH.1080p.WEBRip.x264.AAC-SUNNY](https://www5.yggtorrent.fi/torrent/filmvid%C3%A9o/film/765329-une+sirene+a+paris+2020+french+1080p+webrip+x264+aac-sunny)

Could it be because of the special character "à" ?

**Comment by itsToggle** [comment]
Yeah that's definitely because of the special characters. Add a character replacement rule (/Settings/Scraper Settings/character replacement rules/) that should replace "à" with "a" :)

**Comment by itsToggle** [comment]
I'll see if I can allow accent grave and accent aigu as deviation by default

**Comment by JULIENBZH** [comment]
I've add the rule but plex_debrid only founds 1 release  vs prowlarr giving much more maybe because of other accent... "sirene"'s correct spelling is "sirène".

**Comment by itsToggle** [comment]
I will close this issue, as the solution was adding a character replacement rule

**Comment by Friday13th87** [comment]
Interesting, that this issue was closed, as the given "solution" is not a solution if the indexer search is not working correctly after replacing the characters.
anyway - i have this issue a lot - the matching is not working probably.

for example:
Search string:
a.silent.voice.the.movie.2016

Findings after (!) version filtering (only some examples):
1. [Ryuuga].-.A.Silent.Voice.2016.[1080p-DTS-HD.MA.5.1-REMUX]
2. [Kametsu].A.Silent.Voice.(BD.1080p.HI10.FLAC)
3. A.Silent.Voice:.The.Movie.2016.1080p.BluRay
4. A.Silent.Voice:.The.Movie.2016.720p.BluRay

in this case, all 27 found version have been rejected.
my interpretation:
1. + 2. because of the missing "the.movie"
3. + 4. because there is a ":" in the naming

for 1. and 2. there is no solution most probably and for 3. and 4. i could replace ":" but if i do so, i will have problems in other search strings including ":"

is there any real solution for it? the matching would be much better if the correspondending IDs, IMDB, TVDB etc, would be used - most indexers are replying those informations and the 'arr apps working with them much better i think

Edit:
i saw, that there is a standard rule, number 16, which should actually remove the ":" - it seems that this rule is not working, otherwise there wouldnt be a ":" in the release name...
