### ISSUE TITLE
Error with Premiumize.me

### ISSUE THREAD

**Issue by magnu5** [itsToggle/plex_debrid#27]
I see this in the logs:
[premiumize] error: Src not compatible.

**Comment by itsToggle** [comment]
Hey, could you tell me when this error occurs? I havent encountered this error, could be a broken magnet link. Does the script continue running afterwards and another release is downloaded? Does the service work fine otherwise?

**Comment by magnu5** [comment]
It shows during normal operation, it's just a line in the output so can't tell exactly. It does continue however, I'm not sure anything gets added to Premiumize, everything seems to go to Real-Debrid. I have them both enabled.

**Comment by itsToggle** [comment]
You can change the prefered debrid service by navigating to '/Settings/Debrid Services/Debrid Services/Edit/Edit services/'. There you could move premiumize to the top of the list, if thats what you want. Though, at the moment, RealDebrid cached releases are prefered overall because Ive only implemented a file analysis for Realdebrid.

The error could also occur when checking the debrid services for cached releases. If you want, we could investigate further: You could manually scrape for releases from the main menu (Option 4). The scraped releases should then be displayed as a table. In the 'cached' column you should see on which service/s the releases are cached (e.g. 'RD' and or 'PM'). Are there any PM cached releases displayed?

**Comment by magnu5** [comment]
Yes, this is probably it, shows as cached but will not add it to premiumize and I get that error.

**Comment by itsToggle** [comment]
Thanks! I dont have a premium account on premiumize, which is why I was only able to test everything leading up to actually adding a torrent. I will have a look at the api documentation again :)

**Comment by magnu5** [comment]
No problem happy to test! If you're on reddit you can try asking them nicely for a trial: 
[https://www.reddit.com/r/Premiumize/comments/udkape/premiumize_trial_code_giveaway/](url)

**Comment by itsToggle** [comment]
Ill do that :) In the meanwhile you could try it out with the latest version, perhaps it was just a formatting problem.

**Comment by magnu5** [comment]
Tested, same error.

**Comment by itsToggle** [comment]
Hm, You could try again, but Ive also messaged the moderator and hopefully Ill get premium soon :)

**Comment by itsToggle** [comment]
alright, that one I should have tested before. You could try again with the latest changes. I think Ill just get one moth premium if this still doesnt work... no point in trying to fix the error blindly :D

**Comment by itsToggle** [comment]
Welp, worth a try. Thanks for testing this out, I'll have to get premium myself and find the right formating myself :)

**Comment by itsToggle** [comment]
Just got word from the premiumize mod, I'll get premium in the coming days and should get this working correctly soon :)

**Comment by itsToggle** [comment]
Hey, I finally got around to fixing this isse :)
