### ISSUE TITLE
Add Easynews as debrid 

### ISSUE THREAD

**Issue by SJ50** [itsToggle/plex_debrid#270]
Please add EasyNews to this. It is like debrid service.

**Comment by itsToggle** [comment]
Hi, do you mean easynews.com? This is a usenet service and not a debrid service.

**Comment by SJ50** [comment]
Easynews has search functionality built in, and have ready to stream links. 
It is implemented in these kodi add ons https://github.com/Tikipeter/repository.tikipeter and https://github.com/umbrellaplug/umbrellaplug.github.io

**Comment by itsToggle** [comment]
This is not worth implementing for the following reasons:
I would need to write a scraper and a service module in python. Since I don't see a way to mount this service, that would need to be written aswell. since this service does not work like any other debrid service, I can't simply implement it like the others.

I'd recommend you try to implement this yourself :)
