### ISSUE TITLE
suggestion: rate limiting

### ISSUE THREAD

**Issue by magnu5** [itsToggle/plex_debrid#28]
Some sort of rate limit seems to be needed, got an error on realdebrid: too many connections.
If the watchlist is large (500+) it should maybe be split up in smaller iterations and / or rate limited to x queries per minute or something in order not to get IP blacklisted.

**Comment by itsToggle** [comment]
That's generally a good idea. Though Plex does not seem to need any rate limiting, and I've not encountered any rate limit on realdebrid. There is a connection limit, which i believe is 16 parallel connections, but the requests to realdebrid are usually done fairly quickly and the connection should automatically close afterwards. I'll look into this though, perhaps i forgot to close the connection somewhere. thanks for reporting.
Media items are downloaded sequentially. Multiprocessing is only used when downloading a show, whose seasons/episodes couldn't be found by scraping for the shows name once. 
It will be tricky to implement a rate limiter that works with multiprocessing since the threads can't talk to each other.. I'll try to get this done asap but i might need a bit of time.

**Comment by itsToggle** [comment]
added rate limit for alldebrid link unrestriction in latest release, but will implement a general rate limit handler in the future.

**Comment by itsToggle** [comment]
I will shelve this enhancement for now, as no other issues have been reported since.
And to be honest, I have no idea how I would implement a threaded rate limiter.
