### ISSUE TITLE
optional full plex library scan instead of a partial scan

### ISSUE THREAD

**Issue by spants** [itsToggle/plex_debrid#308]
For large media collections, Plex has trouble refreshing a single directory to add the movie. However a full scan works.

If I use the API without the path (http://[IP address]:32400/library/sections/[Library ID]/refresh?X-Plex-Token=[PlexToken]) it works fine (but is obviously slower for people not affected). See https://www.plexopedia.com/plex-media-server/api/library/scan-single/.
Could this be added as a non-default option please?

**Comment by itsToggle** [comment]
I'll make the partial scan optional, though this doesn't fix the underlying issue. i think I've found the problem though.

Since plex_debrid does not actually know in which folder the new torrent will show up (the "default" folder, the "movies" folder, an entirely different folder that the user has manually created using rclone filtering or a different directory all together because the library is seperated in 4K and HD content), it calls a Plex library scan on all possible locations.

This usually works fine, since a refresh that is called for directories that don't exist finishes instantly. In some cases it seems that Plex is getting confused and doesn't want to refresh the remaining possible locations.

**Comment by itsToggle** [comment]
The culprit seems to be that I'm creating a thread for each possible location. Each thread starts 0.1 seconds behind it's predecessor and checks if the library is currently refreshing every 2 seconds. If the library is not refreshing, a thread calls for a refresh on its location and then closes. It seems that there can be some overlap, so that two threads think they can refresh the library while in reality only one of them will get through.

It's entirely pointless to multithread this, so I'm removing that bit of code which should hopefully fix the underlying issue.

**Comment by itsToggle** [comment]
The script is currently waiting 2 seconds between adding the torrents and refreshing the libraries. I could make that value editable, or you could try to edit the value yourself and try out longer delays. It works for me without any delay at all, I don't know why some of you guys seems to have trouble with it.

If you want to manually edit the value, go to the file `/content/services/plex.py`, line 440 
-or-
find the class `library(classes.library)`, find the child class `refresh(classes.refresh)`, find the function `__new(cls,element)__`

and edit the value for `time.sleep(2)` in the function `i

**Comment by piratsch** [comment]
I will try out to increase that delay and report back, thanks!

I'm at about 2TB Movies and 25TB Shows, maybe this is why it takes a while?

**Comment by itsToggle** [comment]
Alright, Ill make that delay editable :)

**Comment by itsToggle** [comment]
@piratsch added in v2.56
