### ISSUE TITLE
Prowlarr implementation currently broken

### ISSUE THREAD

**Issue by mallah94** [itsToggle/plex_debrid#357]
[Following discord: if you stumble on this please know the current solution is install jackett, add flareresolver, and enable CORS. also make sure to change the timeout from 1 second to 10 seconds for jacket]

Currently any scrapping inside prowlarr (newest version have not tested in previous versions of prowlarr, a recent update was made to prowlarr could be related, will look into it.) is causing problems: `prowlarr error: "resolver couldn't get magnet/torrent for release"`

I have tried everything to get this resolved (fresh installs, tweaking configuration, ...etc)

**Comment by itsToggle** [comment]
This is a known limitation of prowlarr. Prowlarr has very strict rate limits. Switch to Jackett. If you want an explanation for this error, just search the discord server for "resolver":

"Jackett/Prowlarr don't provide the magnet links / torrents for the releases they find directly (for some indexers). They rather provide a link, that then leads to the actual magnet/torrent. Plex_debrid needs to get all magnets/torrents for all releases that were found, in order to check their availability on your debrid service. So plex_debrid tries to resolve all these links in order to get the actual magnets/torrents. If the resolver times out (by default 1 second), or the resolving fails for any other reason, plexdebrid prints that error."

Prowlarr will put insane amounts of sleep times between the requests to resolve their links. If you add 1337x for example, check the prowlarr logs. They will make you wait for 1 minute to resolve a release link.

**Comment by itsToggle** [comment]
This is not something that can be fixed or tweaked. Prowlarr will return what ever releases they allow to be returned until the resolver timeout is reached. That's usually one or two releases. No amount of increased resolver timeout will get you any more than that, since, once again, they put sleep times of actual minutes between these requests.
