### ISSUE TITLE
Plex library not refreshed

### ISSUE THREAD

**Issue by najmsheikh** [itsToggle/plex_debrid#49]
The script successfully detects when an item has been added to the watchlist. It also correctly matches the media and requests it on the debrid service. However, I don't think the request to refresh the library is working correctly. I've reproduced this bug quite a few times -- I have to rescan the library from Plex UI.

I wonder if this is due to a race condition? Perhaps the refresh instruction is sent before the media is ready to be indexed.

**Comment by itsToggle** [comment]
Setting aside the possibility of a misconfiguration of the "movies/shows library section" in plex_debrid, I think you are right about it being a race condition. I can see two causes for this bug: 

A library refresh is called every time a movie/show finishes downloading. When downloading multiple movies/shows in quick succession, a library refresh could be called while the library is still refreshing - causing Plex to ignore the refresh request. This bug I can fix: I will just start a new thread that polls the plex libraries until they have finished refreshing and then make the refresh call.

Another cause could be that rclone has not updated the virtual drive when the library refresh is called. I don't know how to fix this: I want plex_debrid to keep interacting with services through http requests and not through any local, filesystem specific calls. One way to check if rclone has updated the virtual drive would be to check for newly added files from within plex_debrid. That would mean that the drive needs to be mounted on the same system that runs plex_debrid though. I could also just wait a few seconds before making the refresh request, but that would slow down plex_debrid..

**Comment by itsToggle** [comment]
latest commit sends the library refresh call to a new thread. This thread will wait 2 seconds before any refresh call is made, hopefully giving rclone enough time to discover the new files. The thread will also wait until the last library refresh is complete before calling a new refresh (as described in the comment above).

Please report back if you still encounter this issue :)

**Comment by najmsheikh** [comment]
Thanks for the speedy update! I just tried using the latest commit with a couple of tries but unfortunately it did not work as intended. For now, I've just enabled this setting on the server:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/7280352/181867264-1c01c5bd-30aa-4c43-b9c5-ffb98b87dbcf.png">

**Comment by itsToggle** [comment]
Strange.. could you reiterate your issue again? does the refresh call from plex_debrid actually trigger a library refresh of your plex server (e.g. does the status wheel on app.plex.tv start spinning)? 

If it does not, check your plex_debrid "movies/shows library section" settings.

If it does, but no new content is found when refreshing, could you tell me what rclone mounting command you are using?

**Comment by crivera8602** [comment]
So I believe i'm experience the same thing. File gets downloaded but it doesn't show up on the library. i can confirm that its rclone because i'm using the rclone browser and the file doesn't show on the list. I re-mount the drive to see if it would see it and sure enough the file is there. So its rclone that isn't resync once the file is download it. Looking everywhere for a solution but still no luck. Hope that help you with the issue

**Comment by itsToggle** [comment]
@crivera8602 are you using my rclone fork? Or the official rclone software?

If you are using my fork: Ive written the fork to make as little calls to the realdebrid api as possible. Before all pages from /torrents and /downloads are refreshed entirely, a little check is made if the number of torrents has changed. If the number of torrents has not changed, the list of torrents is not updated. This usually works fine, but if you delete a torrent and then add another in quick succession, my rclone fork will not notice a change in the total amount of torrents and therefore will not update the torrents. One way to cause an update if this occurs is to add yet another torrent, so that the total number of torrents changes and a complete refresh is made.

**Comment by crivera8602** [comment]
I'm using your fork. Deleting is fine it's whenever i add that i don't see the movie/tv until i remount the folder

**Comment by itsToggle** [comment]
Strange! Would you mind trying the following mount command? I'm not sure if it makes a difference, but it's worth a try: 

> rclone cmount your-remote: X: --dir-cache-time 10s --vfs-cache-mode full

I've replaced the "=" signs with spaces, perhaps some operating systems don't like the "=" sign notation.

**Comment by crivera8602** [comment]
well progress the file shows without having to remount the folder but its not refreshing in plex. I doubled checked my settings to automatically scan but i have to manually start the scan for it to show the movie/tv

**Comment by itsToggle** [comment]
So far so good. I will change the readme, since the "space" notation seems to work on any os as far as I can tell :)

Have you made sure that the "movies" and "shows" library section numbers are defined correctly inside plex_debrid? 

does the refresh call from plex_debrid actually trigger a library refresh of your plex server? (e.g. does the status wheel on app.plex.tv start spinning, when plex_debrid is printing that the library is being refreshed?)

**Comment by crivera8602** [comment]
1. Have you made sure that the "movies" and "shows" library section numbers are defined correctly inside plex_debrid?
   I don't believe so, i must of skipped a step... any chance you can explain? 

2. does the refresh call from plex_debrid actually trigger a library refresh of your plex server? it does not i have to manually refresh it for it to show up


here is what the debug shows when i added a movie

[2022-08-14 09:24:37.816130] getting entire plex library ... done
[2022-08-14 09:24:37.869939] checking new content ... done
[2022-08-14 09:24:37.969459] scraping sources for query "the.gray.man.2022" ... [2022-08-14 09:24:38.233574] rarbg error: Invalid token. Use get_token for a new one!
[2022-08-14 09:24:38.234588] fetching new token ... done - found 24 releases
[2022-08-14 09:24:45.906460] [realdebrid] error: b'{\n\t"id": "74YMJ464VQORQ",\n\t"uri": "https:\\/\\/api.real-debrid.com\\/rest\\/1.0\\/torrents\\/info\\/74YMJ464VQORQ"\n}'
[2022-08-14 09:24:46.112241] [realdebrid] error: b''
[2022-08-14 09:24:46.112241] [realdebrid] error: (json exception): Expecting value: line 1 column 1 (char 0)
[2022-08-14 09:24:48.140168] [realdebrid] error: b'{\n\t"id": "J7BAK5VEYQ7SY",\n\t"uri": "https:\\/\\/api.real-debrid.com\\/rest\\/1.0\\/torrents\\/info\\/J7BAK5VEYQ7SY"\n}'
[2022-08-14 09:24:48.342274] [realdebrid] error: b''
[2022-08-14 09:24:48.342274] [realdebrid] error: (json exception): Expecting value: line 1 column 1 (char 0)
[2022-08-14 09:24:48.659193] [realdebrid] adding cached release: The.Gray.Man.2022.PROPER.1080p.WEB.H264-PECULATE
[2022-08-14 09:24:48.659193] item: "The Gray Man" removed from chrisitianrivera`s plex watchlist
[2022-08-14 09:24:48.825415] took 10.86s
[2022-08-14 09:24:48.825415] refreshing library section 1
[2022-08-14 09:24:53.834341] updating all plex watchlists ... done
[2022-08-14 09:24:58.929068] updating all plex watchlists ... done
[2022-08-14 09:25:04.003634] updating all plex watchlists ... done
[2022-08-14 09:25:09.107025] updating all plex watchlists ... done
[2022-08-14 09:25:14.211997] updating all plex watchlists ... done

**Comment by itsToggle** [comment]
Okay, the logs don't show anything too wrong. The realdebrid errors are a normal part of the process.

You need to define which library sections should be updated after a successful movie/show download. You can find the setting and instructions here: 
`/Settings/Content Services/Plex/Plex "movies" library` and `/Settings/Content Services/Plex/Plex "shows" library`

**Comment by crivera8602** [comment]
Boom! Library is refreshing! Thank you for your help! Also not sure if your working on the macOS or Linux build but they don't run cmount.. neither populates that command. macOS version doesn't even populate the mount command. Anything else i can help with testing don't hesitate to ask!

**Comment by itsToggle** [comment]
Nice! :)

Thanks for pointing out the rclone fork issue on macos, I have no way of testing the macos build. I will update the readme instructions for the Linux version to use "mount" instead of "cmount".

I'm not sure I will update the rclone fork again.. As far as I know the official realdebrid webdav is still being worked on, and I'll eventually switch to the official version once file deletion works. Perhaps if they are taking too long to make it work I will release an updated version. If that is the case I will comment here again and perhaps ask you if you could test the macos version :)

**Comment by crivera8602** [comment]
one last thing how would you stop the script if lets say you disabled the start in menu? i've tried ctrl + c  but it keeps running

**Comment by crivera8602** [comment]
scratch that i just typed exit and it worked.. man im blind today haha

**Comment by itsToggle** [comment]
Haha, I was about to write that
