### ISSUE TITLE
Request: Integrate/ Merge Trakt Script functionality

### ISSUE THREAD

**Issue by Sea-Wolfe** [itsToggle/plex_debrid#5]
Great Project!  Can't wait to see the future polishing/refinement.

This request is to add in functionality from one of your earlier projects:

[https://github.com/itsToggle/ps-trakt-scraper](url)

These two projects merged would make a super combo!

**Comment by itsToggle** [comment]
Hey, Ive done some coding and wanted to ask what features you are looking for exactly: 

Option 1): The Plex Watchlist will remain the primary way of adding content. The Trakt watchlist is checked for content regulary the Plex watchlist is kept up to date with it. This is relatively easy to do, since the whole script is designed around Plex. This could be done in the next release.

Option 2) The Plex Integration will become optional. The script would essentially become the man-in-the-middle between any sort of watchlist (Plex, Trakt, Google TV, etc.) and Debrid services. This is quite a bit more work, but would make the script a lot more flexible for the different setups users might have.

**Comment by Sea-Wolfe** [comment]
> Hey, Ive done some coding and wanted to ask what features you are looking for exactly:
> 
> Option 1): The Plex Watchlist will remain the primary way of adding content. The Trakt watchlist is checked for content regulary the Plex watchlist is kept up to date with it. This is relatively easy to do, since the whole script is designed around Plex. This could be done in the next release.
> 
> Option 2) The Plex Integration will become optional. The script would essentially become the man-in-the-middle between any sort of watchlist (Plex, Trakt, Google TV, etc.) and Debrid services. This is quite a bit more work, but would make the script a lot more flexible for the different setups users might have.

Option 2 is what I had in mind.  (Because Trakt watchlist is more capable than what Plex offers currently).

You said that this is more work, so I understand if you don’t go that way.  And I am in no position to demand anything.  

Cool project -either way!

**Comment by Sea-Wolfe** [comment]
> Ok I went with option 1 for now.
> 
Nice! Thanks!

My skillset on Linux is very basic, so I’m still hoping someone streamlines the install of your Rclone mod, so I can give this all a whirl.

Hoping someone with the skills steps up! 🤞

**Comment by itsToggle** [comment]
I've now cross-compiled the newest version of the rclone fork for Linux and Mac, if you want to test it out :)

**Comment by Sea-Wolfe** [comment]
> I've now cross-compiled the newest version of the rclone fork for Linux and Mac, if you want to test it out :) 

Awesome, thank you!
