### ISSUE TITLE
Error when items with special characters are in Trakt Watchlist

### ISSUE THREAD

**Issue by joshali1990** [itsToggle/plex_debrid#50]
I get the following error when I have the show "Rap Sh!t" in my Trakt watchlist. I believe the exclamation point is causing the error.

Exception in thread Thread-1312:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/external/plex_rd.py", line 2495, in run
    if plex_watchlist.update() or overseerr_requests.update() or trakt_watchlist.update():
  File "/Volumes/external/plex_rd.py", line 815, in update
    for element in watchlist_shows:
TypeError: 'NoneType' object is not iterable

**Comment by itsToggle** [comment]
hm I could not reproduce this error when adding the show to my trakt watchlist. In the newest version Ive caught the exception that you encountered, but that doesnt fix the underlying issue. Could you please set "debug printing" to "true" by navigating to "/Settings/UI Settings/debug printing" and report back what plex_debrid prints out when you have this show in your watchlist?

While testing I also noticed that the title "Rap Sh!t" is incorrectly renamed for scraping. Its renamed to "Rap.Sht.S01" and not "Rap.Shit.S01", since the "!" is simply removed and not replaced by the letter "i". Ive worked in a quick fix for that aswell :)

**Comment by joshali1990** [comment]
I'm honestly not sure if it was adding that show to my watchlist or updating to the latest version of your script. So probably not related. Thanks - I'll download the latest version and see if I get any errors.

**Comment by itsToggle** [comment]
it could also be that you need to re-authorize your trakt account. The token might have expired. Ive not yet implemented a method to automatically renew the token, its on the long list of things to fix though.

**Comment by itsToggle** [comment]
You might need to update once more, I just realized I missed a line of code that could also cause the reported exception

**Comment by joshali1990** [comment]
The update seems to have died the error thanks!
