### ISSUE TITLE
[Question] Is it like RealDebrid

### ISSUE THREAD

**Issue by Drjacky** [itsToggle/plex_debrid#510]
So, by using this project, we could have our own RealDebrid on our own host/VPS?
I'm looking for such a project that I could do what RealDebrid does, on my own VPS.

**Comment by itsToggle** [comment]
not quite sure what you mean - this project uses realdebrid and other debrid services but it doesnt replace them. These debrid services are basically like a shared seedbox. If any user tells realdebrid to download a torrent to their servers, all other users have access to that downloaded torrent aswell. Thats why content you add is mostly available instantly, because chances are someone else wanted to download that torrent already.
This project takes advantage of the instant availability and the direkt streaming capabilities of these services. It allows you to create and maintain a personal media server consisting of debrid-hosted content.
