### ISSUE TITLE
Wrong release date

### ISSUE THREAD

**Issue by mash2k3** [itsToggle/plex_debrid#517]
![image](https://github.com/itsToggle/plex_debrid/assets/1356023/de866174-3d8e-4b2c-8211-83f8287761f8)
![image](https://github.com/itsToggle/plex_debrid/assets/1356023/c91bc04c-34ca-42a0-8ff9-69fdf9ddb8ae)

**Comment by itsToggle** [comment]
This is most likely because Trakt did not specify the type of release (digital, cinema, etc). PD will assume that it's a regular movie, releasing to cinemas on that date. This will cause PD to default to a 60 day delay. PD will check for digital or Bluray release dates for that movie every 30 minutes and will adjust the date on which the download will be attempted accordingly.

You could set up a version that is triggered by the "UFC" in the movie title and give that a different airtime offset to remedy this.
