### ISSUE TITLE
Don't add "SAMPLE" files

### ISSUE THREAD

**Issue by piratsch** [itsToggle/plex_debrid#7]
Not sure if your script handles the part of selecting which files of the torrents to download.

It would be nice if files containing "SAMPLE" in the title could be excluded (as they show up as movies...)

Thank you!

**Comment by piratsch** [comment]
Thanks! I'll let you know in a couple of days if it works.

BTW: I've created a dockerized version for myself. It's not yet finished to "ship" to other people (permission weirdness because fuse is used to mount the RD directory), but I'll probably open a PR sometime this month if you're interested.

**Comment by itsToggle** [comment]
Thats awesome! Thanks 👍
I will update the rclone fork again in the coming days, making the realdebrid Implementation a seperate remote so premiumize isnt owerwritten anymore.

**Comment by Sea-Wolfe** [comment]
> piratsch

I'm interested in the dockerized version! :)

I'll gladly be a beta tester after you iron out the permissions issue!

**Comment by Sea-Wolfe** [comment]
> Thats awesome! Thanks 👍 I will update the rclone fork again in the coming days, making the realdebrid Implementation a seperate remote so premiumize isnt owerwritten anymore.

👍
If you do a PR, do you think Rclone will merge your RD addition into their main branch?

I'm I am just trying to figure out if they would think this is too "hacky" since RD doesn't officially promote themselves as "Cloud Storage."

**Comment by itsToggle** [comment]
Yeah Ive contacted rclone before, and they would have liked for realdebrid to be an "optional setting" when setting up a premiumize remote. That sadly doesnt work since there is quite a bit of stuff that I had to change. They are less enthusiastic about realdebrid being a seperate remote, since that means they will have to maintain yet another remote.

Once Im done with my rclone fork Ill let you guys know how they react.
